spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root0327

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files: classpath:sql/init-import.sql # dummy sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: true


